server:
  port: 8070

spring:
  main:
    banner-mode: off
  application:
    name: discovery-api
  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost
  client:
    fetchRegistry: false
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/