server:
  port: 8080

spring:
  main:
    banner-mode: off
  profiles:
    active: git
  application:
    name: config-api
  cloud:
    config:
      server:
        git:
          defaultLabel: main
          tryMasterBranch: false
          timeout: 3
          uri: https://github.com/alexandresoliveiragft/microservices
          deleteUntrackedBranches: true
          searchPaths:
            - 'config-api-files/{application}/{profile}'
  security:
    user:
      name: dev
      password: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  file:
    path: "@project.basedir@/.."
    name: "devops/volumes/java-logs/${spring.application.name}.log"
  max-size: 10MB
  max-history: 1
  level:
    dev:
      alexandreoliveira: DEBUG