server:
  port: 8080

spring:
  main:
    banner-mode: off
  profiles:
    active: git
  application:
    name: config-api
  cloud:
    config:
      server:
        git:
          defaultLabel: main
          tryMasterBranch: false
          timeout: 3
          uri: https://github.com/alexandresoliveiragft/microservices
          deleteUntrackedBranches: true
          searchPaths:
            - 'config-api-files/{application}/{profile}'
  security:
    user:
      name: dev
      password: dev