global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'accounts-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8081' ]
  - job_name: 'cards-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8082' ]
  - job_name: 'employees-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8083' ]
  - job_name: 'gateway-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8060' ]
  - job_name: 'discovery-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8070' ]
  - job_name: 'config-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'localhost:8080' ]