spring:
  main:
    banner-mode: off
  application:
    name: employees-api
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://dev:dev@localhost:8080'
  cloud:
    config:
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
