spring:
  main:
    banner-mode: off
  application:
    name: employees-api
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://dev:dev@localhost:8080'
  cloud:
    config:
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Bank - Employees API"
    description: "Employees microservice for bank dashboard"
    version: "0.0.1-SNAPSHOT"

logging:
  file:
    path: "@project.basedir@/.."
    name: "devops/volumes/java-logs/${spring.application.name}.log"
  max-size: 10MB
  max-history: 1
  level:
    dev:
      alexandreoliveira: DEBUG

