spring:
  main:
    banner-mode: off
  application:
    name: discovery-api
  profiles:
    active: dev
  config:
    import: 'optional:configserver:http://dev:dev@localhost:8080'
  cloud:
    config:
      label: main

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

logging:
  file:
    path: "@project.basedir@/.."
    name: "devops/volumes/java-logs/${spring.application.name}.log"
  max-size: 10MB
  max-history: 1
  level:
    dev:
      alexandreoliveira: DEBUG
