server:
  port: 8081
spring:
  main:
    banner-mode: off
  application:
    name: accounts-api
  profiles:
    active: dev
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/aosoluti-microservices-accounts-api-db
    username: dev
    password: dev
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 5000
      pool-name: AccountsApiHikariPool
  flyway:
    url: jdbc:postgresql://localhost:5432/aosoluti-microservices-accounts-api-db
    user: dev
    password: dev
    encoding: UTF-8
    baseline-on-migrate: true
    clean-disabled: true
    locations:
      - "db/migrations/postgresql"
    enabled: true
  servlet:
    multipart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace

resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 500
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      ignoreExceptions:
        - java.lang.NullPointerException
      retryExceptions:
        - java.util.concurrent.TimeoutException

resilience4j.ratelimiter:
  configs:
    default:
      timeoutDuration: 1000
      limitRefreshPeriod: 5000
      limitForPeriod: 1