server:
  port: 8081

spring:
  main:
    banner-mode: off
  application:
    name: cards-api
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5434/aosoluti-microservices-cards-api-db
    username: dev
    password: dev
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
      idle-timeout: 10000
      max-lifetime: 60000
      connection-timeout: 5000
      pool-name: CardsApiHikariPool
  flyway:
    url: jdbc:postgresql://localhost:5434/aosoluti-microservices-cards-api-db
    user: dev
    password: dev
    encoding: UTF-8
    baseline-on-migrate: true
    clean-disabled: true
    locations:
      - "db/migrations/postgresql"
    enabled: true
  servlet:
    multipart:
      enabled: false
  jackson:
    default-property-inclusion: NON_NULL
  redis:
    database: 0
    host: localhost
    port: 6379
    password: dev
    timeout: 60000

api:
  clients:
    account-api: http://localhost:8080
  cache:
    ttl:
      cards-api-card: 10

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
