server:
  port: 8060

spring:
  application:
    name: gateway-api
  profiles:
    active: dev

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/